name: fide

services:

  db:
    image: postgres:17.4-alpine
    container_name: fide_postgres
    volumes:
      - ./.containers_data/postgres:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      POSTGRES_DB: fide
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dummy
    ports:
      - 5432:5432
    networks:
      - fide
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: fide_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8180:8080
    networks:
      - fide
    profiles:
      - adminer
    restart: unless-stopped

volumes:
  .containers-data: {}

networks:
  fide:
    driver: bridge
