version: "3.8"
services:

  db:
    image: postgres:16.2-alpine3.19
    container_name: fide_postgres
    volumes:
      - ./.containers_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fide
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dummy
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  .containers-data: {}
