addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"         % "0.12.1")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.24")
addSbtPlugin("com.github.sbt"               % "sbt-native-packager"  % "1.11.0")
addSbtPlugin("nl.gn0s1s"                    % "sbt-dotenv"           % "3.0.1")
addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.3")
addSbtPlugin("org.typelevel"                % "sbt-tpolecat"         % "0.5.2")
addSbtPlugin("io.gatling"                   % "gatling-sbt"          % "4.9.2")
addSbtPlugin("com.github.sbt"               % "sbt-release"          % "1.4.0")
